name: Snyk security scan
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Adjust the version as needed
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        with:
          args: --sarif-file-output=snyk.sarif ./WWA-backend-master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Upload SARIF to GitHub Security Center
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
