name: SonarQube Analysis
on:
  push:
    branches:
      - main
jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: WWA-backend-master

      - name: Run Jest tests with coverage
        run: npm test -- --coverage
        working-directory: WWA-backend-master

      - name: Set up JDK 17 for SonarQube Scan
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Snyk Security Scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true
        working-directory: WWA-backend-master

      - name: Convert Snyk results to SARIF
        run: snyk-to-sarif -i snyk-results.json -o snyk-results.sarif
        working-directory: WWA-backend-master

      - name: Upload Snyk results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: WWA-backend-master/snyk-results.sarif
