name: SonarQube Analysis
on:
  push:
    branches:
      - main
jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: WWA-backend-master

      - name: Run Jest tests with coverage
        run: npm test -- --coverage
        working-directory: WWA-backend-master

      - name: Set up JDK 17 for SonarQube Scan
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=group2
            -Dsonar.sources=WWA-backend-master
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.javascript.lcov.reportPaths=WWA-backend-master/coverage/lcov.info

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Snyk Security Scan
        run: |
          snyk test --org=shreyashettys202 --project-name=Group2 --severity-threshold=high --json --file=WWA-backend-master/package.json > snyk-results.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true
        working-directory: WWA-backend-master

      - name: Convert Snyk results to SARIF
        run: snyk-to-sarif -i snyk-results.json -o snyk-results.sarif
        working-directory: WWA-backend-master

      - name: Upload Snyk results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: WWA-backend-master/snyk-results.sarif
