name: SonarQube Analysis
on:
  push:
    branches:
      - main
jobs:
  sonarqube_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: cd WWA-backend-master && npm install
      - name: Run Jest tests with coverage
        run: cd WWA-backend-master && npm test -- --coverage || true
        # Run tests with coverage, ignoring failures with '|| true'
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@7295e71c9583053f5bf40e9d4068a0c974603ec8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args:
            -Dsonar.projectKey=group2
            -Dsonar.sources=.
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.javascript.lcov.reportPaths=WWA-backend-master/coverage/lcov.info
            # Add other SonarQube analysis parameters as needed
      # Install Snyk CLI and Run Snyk Security Scan
     # - name: Install Snyk CLI
      #  run: npm install -g snyk
     #   working-directory: ./WWA-backend-master
      # Add the Snyk security scan step
      - name: Snyk Security Scan
        uses: snyk/actions/node@master
        continue-on-error: true
        working-directory: ./WWA-backend-master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: 
            --severity-threshold=high
            --sarif-file-output=snyk.sarif
       # run: snyk test --org=shreyashettys202 --project-name=Group2 --json || true
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif       
